### ISSUE TITLE
Feature request: using a different IRC nick

### ISSUE THREAD

**Issue by dak1n1** [tulak/zabbirc#13]
My IRC nick does not match my Zabbix username. I would like a way to configure zabbirc to know who I am, so I can ack alerts and run commands.

**Comment by mmahut** [comment]
@dak1n1 it actually takes your IRC ident, can you try to change it? I have a similar case, my irc nick is 'marek' but the username is 'mmahut'.

**Comment by dak1n1** [comment]
@mmahut Sorry I didn't see this comment until now. I'm new to github conversations.

So my IRC username is actually 'sedgar', which is the same as my zabbix username. It sounds like it should work then. Am I misunderstanding?
